name:                state-machine-example
version:             0.1.0.0
github:              "githubuser/state-machine-example"
license:             BSD3
author:              "Pedro Vasconcelos"
maintainer:          "pbv@dcc.fc.up.pt"
copyright:           "2024 Pedro Vasconcelos"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Use example for quickcheck-state-machine
category:            Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/state-machine-example#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- random
- tree-diff
- QuickCheck
- quickcheck-state-machine

executables:
  state-machine-example-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts 
    extra-libraries: queue
    extra-lib-dirs: ./lib


